# Generated by Django 5.2 on 2025-04-20 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(default=5, help_text='Passenger capacity of the vehicle', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_efficiency',
            field=models.FloatField(default=0.0, help_text='Fuel efficiency in km/l', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
