# Generated by Django 5.2 on 2025-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('field', 'Field Car'), ('pool', 'Pool Car')], default='field', help_text='Vehicle category (Field or Pool car)', max_length=10),
        ),
    ]
