# Generated by Django 5.1.7 on 2025-04-27 14:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_milage', models.DecimalField(decimal_places=1, default=0.0, help_text='Current mileage in km/miles (1 decimal place)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('end_milage', models.DecimalField(decimal_places=1, default=0.0, help_text='Current mileage in km/miles (1 decimal place)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Onprogress', 'Onprogress'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignemt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='assignment.vehicle_assignment')),
            ],
        ),
    ]
