# Generated by Django 5.1.7 on 2025-04-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_trips'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='end_milage',
            new_name='end_mileage',
        ),
        migrations.RenameField(
            model_name='trips',
            old_name='start_milage',
            new_name='start_mileage',
        ),
    ]
