# Generated by Django 5.2 on 2025-04-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_rename_end_milage_trips_end_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
