# Generated by Django 5.2 on 2025-05-01 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_trips_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trips',
            old_name='assignemt',
            new_name='assignment',
        ),
    ]
