# Generated by Django 5.2 on 2025-04-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('employee', 'Employee'), ('driver', 'Driver'), ('admin', 'Administrator'), ('director', 'Director')], default='employee', max_length=20, verbose_name='role'),
        ),
    ]
