# Generated by Django 5.2 on 2025-12-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unencrypted_password',
            field=models.CharField(blank=True, help_text='Stores unencrypted password. Use only for temporary passwords.', max_length=128, null=True, verbose_name='unencrypted password'),
        ),
    ]
