# Generated by Django 5.1.7 on 2025-04-24 11:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purpose', models.CharField(max_length=255)),
                ('urgency', models.CharField(choices=[('Regular', 'Regular'), ('Emergency', 'Emergency'), ('Priority', 'Priority')], default='Regular', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved by Department'), ('Rejected', 'Rejected by Department'), ('Cancelled', 'Cancelled by Requester'), ('Completed', 'Fulfilled Successfully'), ('Assigned', 'Assigned to Driver')], default='Pending', max_length=10)),
                ('passenger_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('passenger_names', models.JSONField(blank=True, default=list, help_text='List of passenger names in JSON format')),
                ('department_approval', models.BooleanField(default=False)),
                ('department_approval_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('department_approver', models.ForeignKey(blank=True, limit_choices_to={'role': 'director'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Request',
                'verbose_name_plural': 'Vehicle Requests',
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
    ]
