# Generated by Django 5.1.7 on 2025-04-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_request',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='vehicle_request',
            name='start_time',
        ),
        migrations.AddField(
            model_name='vehicle_request',
            name='duration',
            field=models.JSONField(blank=True, default=list, help_text='List of start and end time names in JSON format'),
        ),
    ]
