# Generated by Django 5.1.7 on 2025-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_remove_vehicle_request_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_request',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
