# Generated by Django 5.1.7 on 2025-04-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_vehicle_request_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle_request',
            name='duration',
        ),
        migrations.AddField(
            model_name='vehicle_request',
            name='end_dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_request',
            name='start_dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Assigned', 'Assigned')], default='Pending', max_length=10),
        ),
    ]
